apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dmp
  name: sw-performance-test-eureka-server
  labels:
    app: sw-performance-test-eureka-server
spec:
  selector:
    matchLabels:
      app: sw-performance-test-eureka-server
  template:
    metadata:
      labels:
        app: sw-performance-test-eureka-server
    spec:
      imagePullSecrets:
        - name: registry-pull
      containers:
        - image: wutang/eureka-server:1.0
          name: sw-performance-test-eureka-server
          resources:
            requests:
              memory: "1024Mi"
              cpu: "500m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
          ports:
            - containerPort: 8761
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dmp
  name: sw-performance-test-service-a
  labels:
    app: sw-performance-test-service-a
spec:
  selector:
    matchLabels:
      app: sw-performance-test-service-a
  template:
    metadata:
      labels:
        app: sw-performance-test-service-a
    spec:
      imagePullSecrets:
        - name: registry-pull
      containers:
        - image: wutang/service-a:1.0
          name: sw-performance-test-service-a
          resources:
            requests:
              memory: "4096Mi"
              cpu: "2000m"
            limits:
              memory: "4096Mi"
              cpu: "2000m"
          ports:
            - containerPort: 8762
          env:
            - name: EUREKA_URL
              value: "http://eureka-server:8761/eureka"
            - name: SW_AGENT_NAME
              value: "service-a"
            - name: EUREKA_URL
            - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
              value: dev-dmp-sw-performance:11800
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dmp
  name: sw-performance-test-service-b
  labels:
    app: sw-performance-test-service-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sw-performance-test-service-b
  template:
    metadata:
      labels:
        app: sw-performance-test-service-b
    spec:
      imagePullSecrets:
        - name: registry-pull
      imagePullPolicy: Always
      containers:
        - image: wutang/service-b:1.0
          name: sw-performance-test-service-b
          resources:
            requests:
              memory: "4096Mi"
              cpu: "2000m"
            limits:
              memory: "4096Mi"
              cpu: "2000m"
          ports:
            - containerPort: 8763
          env:
            - name: EUREKA_URL
              value: "http://eureka-server:8761/eureka"
            - name: SW_AGENT_NAME
              value: "service-b"
            - name: EUREKA_URL
            - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
              value: dev-dmp-sw-performance:11800
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dmp
  name: sw-performance-test-service-c
  labels:
    app: sw-performance-test-service-c
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sw-performance-test-service-c
  template:
    metadata:
      labels:
        app: sw-performance-test-service-c
    spec:
      imagePullSecrets:
        - name: registry-pull
      imagePullPolicy: Always
      containers:
        - image: wutang/service-c:1.0
          name: sw-performance-test-service-c
          resources:
            requests:
              memory: "4096Mi"
              cpu: "2000m"
            limits:
              memory: "4096Mi"
              cpu: "2000m"
          ports:
            - containerPort: 8764
          env:
            - name: EUREKA_URL
              value: "http://eureka-server:8761/eureka"
            - name: SW_AGENT_NAME
              value: "service-c"
            - name: EUREKA_URL
            - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
              value: dev-dmp-sw-performance:11800
---
apiVersion: v1
kind: Service
metadata:
  name: sw-performance-test-eureka-server
spec:
  type: NodePort
  ports:
    - port: 8761
  selector:
    app: sw-performance-test-eureka-server
---
apiVersion: v1
kind: Service
metadata:
  name: sw-performance-test-service-a
spec:
  type: NodePort
  ports:
    - port: 8762
  selector:
    app: sw-performance-test-service-a
---
apiVersion: v1
kind: Service
metadata:
  name: sw-performance-test-service-b
spec:
  type: NodePort
  ports:
    - port: 8763
  selector:
    app: sw-performance-test-service-b
---
apiVersion: v1
kind: Service
metadata:
  name: sw-performance-test-service-c
spec:
  type: NodePort
  ports:
    - port: 8764
  selector:
    app: sw-performance-test-service-c
