version: '3.3'
services:
  eureka-server:
    image: wutang/eureka-server:2.0
    container_name: eureka-server
    restart: always
    ports:
      - 8761:8761
  service-a:
    image: wutang/service-a:2.0-agent
    container_name: service-a
    depends_on:
      - eureka-server
    links:
      - eureka-server
    restart: always
    environment:
      EUREKA_URL: http://eureka-server:8761/eureka
      SW_AGENT_NAMESPACE: test
      SW_AGENT_NAME: service-a
      SW_AGENT_COLLECTOR_BACKEND_SERVICES: 10.8.0.65:11800
    ports:
      - 8762:8762
  service-b:
    image: wutang/service-b:2.0-agent
    container_name: service-b
    depends_on:
      - eureka-server
      - service-a
    links:
      - eureka-server
      - service-a
    restart: always
    environment:
      EUREKA_URL: http://eureka-server:8761/eureka
      SW_AGENT_NAMESPACE: test
      SW_AGENT_NAME: service-b
      SW_AGENT_COLLECTOR_BACKEND_SERVICES: 10.8.0.65:11800
    ports:
      - 8763:8763
  service-c:
    image: wutang/service-c:2.0-agent
    container_name: service-c
    depends_on:
      - eureka-server
      - service-b
    links:
      - eureka-server
      - service-b
    restart: always
    environment:
      EUREKA_URL: http://eureka-server:8761/eureka
      SW_AGENT_NAMESPACE: test
      SW_AGENT_NAME: service-c
      SW_AGENT_COLLECTOR_BACKEND_SERVICES: 10.8.0.65:11800
    ports:
      - 8764:8764
